#ifndef LIGHTPROTOCOL_GLOBAL_H
#define LIGHTPROTOCOL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIGHTPROTOCOL_LIBRARY)
#  define LIGHTPROTOCOL_EXPORT Q_DECL_EXPORT
#else
#  define LIGHTPROTOCOL_EXPORT Q_DECL_IMPORT
#endif

#endif // LIGHTPROTOCOL_GLOBAL_H
